services:
  jobmanager:
    image: apache/flink:1.20-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8088:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: apache/flink:1.20-scala_2.12-java11
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    depends_on:
      - jobmanager
    deploy:
      replicas: 2
    volumes:
      - ..:/app